### ISSUE TITLE
Dont`n work Flaxbeard Steam Power Support

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/ModTweaker2#239]
I add recipes to the wiki but nothing works. there are no errors.

**Comment by jaredlll08** [comment]
FSP is no longer supported.

**Comment by Tsyklop** [comment]
@jaredlll08 A will?

**Comment by jaredlll08** [comment]
Pardon? It IS NOT supported.

**Comment by Yulife** [comment]
Then drop the support of it instead of keeping it which creates cconfusion :)

**Comment by Voidi** [comment]
@jaredlll08 Whats the problem with FSP that it don't work anymore?

**Comment by jaredlll08** [comment]
last I checked, the mod didn't have an api for recipe changes, I went into their irc and got told to make an issue on github, I did... and if I'm correct, it is STILL open, and this was months ago.

**Comment by jaredlll08** [comment]
https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/issues/223
yep!

**Comment by trollworkout** [comment]
flaxbeard is in a weird state because is not really being developed anymore. the current maintainer simply sits on it and that's pretty much all he's done since he took over the mod.

**Comment by jaredlll08** [comment]
Well I removed the support. And don't have any plans on bringing it back.

**Comment by Tsyklop** [comment]
@jaredlll08 remove info from Wiki)

**Comment by trollworkout** [comment]
but you will leave what you have thus far in right? i mean is not fully working but at least ppl can use what you have to get something out of it.

**Comment by jaredlll08** [comment]
First of all, don't tell me what to do, the wiki is OPEN all you need it an account, a free account. so instead of telling me what t do, why don't you do it.
@trollworkout Nope, because then I get "Why isn't FSP support finished?!?"

**Comment by trollworkout** [comment]
i am not telling you what to do. i am asking you. was a question. 
NOTE THIS IS A QUESTION
will you leave what you have thus far in?
yes / no
NOTE THIS IS END OF QUESTION

**Comment by trollworkout** [comment]
i have to make a warning people get so defensive. relax my man. was just a question.

**Comment by Tsyklop** [comment]
@jaredlll08 I can not edit anything in the wiki ... I can not even register ...

**Comment by jaredlll08** [comment]
@trollworkout that was directed at @Tsyklop sorry.
I do not want to leave it in, it has been broken for months and people will ask "why isn't this working", also all implementation is currently broken, if you realize it or not, @Yulife checked a while ago.

**Comment by Dream-Master** [comment]
So i can delte the link if you want. My account works.

**Comment by jaredlll08** [comment]
Also @Tsyklop You should be able to register, look in the top right.

**Comment by Dream-Master** [comment]
So it change it to
Flaxbeard's Steam Power: Not supported anymore.

**Comment by trollworkout** [comment]
is ok guys we get it.

problem is he's gonna get 100000 questions being like WHY is this not supported and he has to say the same stuff over and over. just spread the word and help the guy out just be like is not supported because the API is incomplete and no word from the dev.

**Comment by Yulife** [comment]
If the API ever gets fixed we'll probably get back to it.

**Comment by jaredlll08** [comment]
Nope. I am not touching FSP until 2 things happen. It gets a new author/maintainer and it gets rewritten. I asked in irc for help about adding recipes, they told me to go to git, I went to git, over 5 months nothing.

**Comment by Yulife** [comment]
That is what I was saying, silly :wink:

**Comment by elifoster** [comment]
I'm glad that mod developers are expected to devote their lives to writing mods :unamused: 

I'd like to point out a few things:
* The code was given to the current team with little to no documentation or any explanation of how anything works. This was followed by the old maintainer vanishing after about 3 weeks of it being given to me.
* The code is a mess. It uses copy-pastes from Minecraft itself, terrible styling (I've tried to fix this up a bit in the areas I use most), and just awful conventions.
* The amount of bugs, and the severity of all the bugs, take priority over API and feature requests. First take the previous points into account, then take a look at all the bugs that the mod has. Try to understand that.
* We have, on any given day, about 70 issues total. Issues are frequently getting reported and added to the issue tracker, which pushes old issues further down the Waffle (I use Waffle IO for issue management). If you notice that your issue is being ignored/put to the backburner, instead of complaining about it on some other thread that I would almost have no idea of finding, just post on it and say "Hey, we're going to drop support if you don't add this." That would probably motivate me to do it. Honestly, I completely forgot you even put an issue on the tracker because it's on the 2nd page, and was probably on the 3rd for a large chunk of time.
* One's life should not be expected to be devoted to modding a video game. People have other priorities. Love-life, college, and job-hunting are some of the things in my life specifically that take priority over modding Minecraft.

Instead of bashing myself and the rest of the team, perhaps you could just submit a pull request for the feature if we are taking too long to get to it.

Also, if you'd like I could actually look into it. Though I don't want to do it if you're going to indefinitely refuse FSP support despite the API having the features you need. I'd just like to know whether I should actually work on that API or not.

**Comment by jaredlll08** [comment]
First of all, I never said that I would never touch it, I said that I would wait for 2 things to happen.
Secondly, I went into your irc channel asking about it, I got told to make an issue, and all I was doing was asking how the api works, not asking you guys to do ANYTHING but explain how the api works, something that could have easily been done in irc, but no, I got told to make an issue.
After I got a response back:
`
<Jared>	hey, could someone here help me please, I have taken over modtweaker and joshie left the FSP support in a very bad state, so could someone please tell me how I would remove a crucible recipe...
Feb 03 08:42:57 <SatanicSanta>	I should probably know how to do that.
Feb 03 08:43:01 <SatanicSanta>	Unfortunately I don't
Feb 03 08:47:29 <Jared>	SatanicSanta, any idea who would know?
Feb 03 08:47:47 <SatanicSanta>	Jared: Is it on FSP's side or MT's side?
Feb 03 08:51:07 <Jared>	SatanicSanta, pretty sure it is FSP]
Feb 03 08:51:35 <SatanicSanta>	I shall take a look in the API then
Feb 03 08:52:27 <SatanicSanta>	Jared: It does not seem like there is a way, with the current FSP API, to remove Crucible recipes.
Feb 03 08:53:07 <Jared>	SatanicSanta, ok thanks for checking
Feb 03 08:53:24 <SatanicSanta>	You could always open an issue about it
Feb 03 08:56:28 <Jared>	SatanicSanta, ok cool
`
That response is basically saying "No addon will work since you can't add crucible recipes" I personally consider that high priority, addons make mods survive longer, they add more content and all of that, but this issue has been there for months on end. I just looked at your repo, I fixed 2 high priority issues(you're welcome), and looked at the other high priority, more than half of them have no information and are just sitting there. out of the 71 issues that you have, 11 of them are ready, 2 are invalid. 6 are unconfirmed and 2 are won't fix, then there are the 2 I just fixed, that leaves you with 48 issues so please don't say that you have 70 issues on average when nearly half of them just need to be closed.

And please don't forget, I AM a mod dev, I understand that you have a life, but leaving an issue that breaks addons for this long is insane.

Also you think you have it rough? I was left with this code, where nearly half of the mods weren't working, and joshie was less than helpful with it, and I didn't have a team, I was on my own, fixing this mod that was left for 3 months without anyone coding it, you at-least had a team that would make it go quicker / smoother.

Also doing newer issues first is literally the worst way to do it, for all you know, there could be a massive dupe bug on the second page, and by doing issues first you will never see it, since it isn't on the first page, and people keep on reporting bugs.

And once again, let me just say, I don't expect mod devs to devote their life to modding, for most it is a hobby, but the fact that you have a team to help you should make things easier and quicker, if it doesn't then you need to reevaluate if being in a team is the best option.

I looked at how to fix the feature, and I didn't understand any of it.

And to end it off with, I had no intention to bash anyone, all I was saying is that I don't want to add support until I can add all the support, in terms of all the machines, because lets say I add support for machine X, then people will say, "Where is support for machine Y?" and I would get bombarded with that question, it happened when I added support for the AE2 inscriber but not the grinder, so I am sorry if it seemed like I was bashing you guys, I did not mean to.

**Comment by xbony2** [comment]
Team? Not really, Santa does most of everything. I've fixed gradle and a bug or two, but most of the actual work is on Santa.

I think it's a bit silly that you're basing off a response that was so many months ago. If it had been requested again sooner, we could of probably focused on it; although, this itself is a request of sorts.

**Comment by jaredlll08** [comment]
He said team, so I said team, and Im not refusing FSP support, that would
be stupid.

**Comment by elifoster** [comment]
@xbony2 Well you're *supposed to* be focusing on crossmod things :wink: 

@jaredlll08 So if I add the APIs will support be re-added, despite the change of maintainers which isn't going to happen anytime soon?

**Comment by jaredlll08** [comment]
That was badly worded, the author thing, but yes, I have nothing wrong with
you guys.

**Comment by elifoster** [comment]
Ok, cool. I'll probably work on it today. Esteemed-Innovation/Flaxbeards-Steam-Power#327

**Comment by InfinityRaider** [comment]
For what its worth, I made a MineTweaker and NEI handler for that mod a while ago because I needed it. Feel free to do with it what you want, just dropping it here: https://github.com/InfinityRaider/SteamPowerAdditions/blob/master/src/main/java/com/InfinityRaider/SteamPowerAdditions/compatibility/minetweaker/SteamSmasher.java

**Comment by ghost** [comment]
the api was completed in the end but i guess this was never ultimately added because Minecraft moved on. 1.7.10 is forgotten by many but still the best Minecraft version for mods. I got about x 10 times more things in my modded 1.7.10 world than in vanillla or even modded 1.12. Flaxbeard mostly works in MT3 for example you can in fact add alloys dips and drops into the crucible but some things don't like removing recipes from steam heater get "stuck" because last ModTweaker 3 version has the incomplete steamcraft api 🤣  All it needed was one final 0.9.7  release to include the api changes from Flaxbeard. Ah well 👍  S'all good
