### ISSUE TITLE
[Request] Update Crafting Handler of Forestry Machines

### ISSUE THREAD

**Issue by Yulife** [jaredlll08/ModTweaker2#35]
For @jaredlll08 
@mezz changed some stuff with the Carpenter regarding the box slot. Now a custom recipe will not work.
No error is thrown.

[Script](http://paste.ee/p/KIgEM)

**Comment by mezz** [comment]
I did not change anything with Carpenter addRecipe API, it should be the same. It might be because Minetweaker changed their addRecipe method? https://github.com/jaredlll08/ModTweaker2/commit/e36dd43b18697669e44bbe0a8b8e6986d11b9df2

**Comment by jaredlll08** [comment]
looked at the code, no idea regarding what was changed...

**Comment by mezz** [comment]
The box slot has changed so that it will only accept boxes that have been added in the recipe manager's recipes. The recipe manager keeps a list of valid boxes, it adds them [in this method](https://github.com/ForestryMC/ForestryMC/blob/5b8b0c78b0fefa53be6d6bb08c27a647bf4ce194/src/main/java/forestry/factory/gadgets/MachineCarpenter.java#L171-L180):

```java
		@Override
		public void addRecipe(int packagingTime, FluidStack liquid, ItemStack box, ItemStack product, Object materials[]) {
			recipes.add(new Recipe(packagingTime, liquid, box, ShapedRecipeCustom.createShapedRecipe(product, materials)));
			if (liquid != null) {
				recipeFluids.add(liquid.getFluid());
			}
			if (box != null && !isBox(box)) {
				boxes.add(box);
			}
		}
```

I'm not sure how you guys do things but I'll help if I can.

**Comment by Yulife** [comment]
Thanks!!! =]
