### ISSUE TITLE
Railcraft Machines not accepting ore dictionary entry for InputStack

### ISSUE THREAD

**Issue by Bunsan** [jaredlll08/ModTweaker2#64]
I'm attempting to modify a recipe for the Coke Oven, Blast Furnace, Rolling Machine and Rock Crusher.  

I believe the Rolling Machine error is a bug. My rolling machine script is 

mods.railcraft.Rolling.addShaped(<Railcraft:part.plate> * 2, [[<ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>]]);

It returns ERROR: Error executing MineTweakerRecipeMaker: null. It works as expected with minecraft:iron_ingot.

The rock crusher, coke oven and Blast Furnace I believe are intended behaviour as there are matchDamage and matchNBT boolean parameters.  However there would be value to allow a OreDict entry with false values for matchDamage and matchNBT. The script is

mods.railcraft.CokeOven.addRecipe(<ore:logWood>, false, false, <terrafirmacraft:item.coal:1>, <liquid:creosote> * 100, 100);
Returns ERROR: /scripts/Crafting.zs:890 > a method available but none matches the parameters (minetweaker.oredict.IOreDictEntry, bool, bool, minetweaker.item.IItemStack[], minetweaker.liquid.ILiquidStack,int)

mods.railcraft.BlastFurnace.addRecipe(<ore:ingotIron>, false, false, 130, <terrafirmacraft:item.Steel Ingot>);
Returns ERROR: /scripts/Crafting.zs:886 > a method available but none matches the parameters (minetweaker.oredict.IOreDictEntry, bool, bool, int, minetweaker.item.IItemStack[])

mods.railcraft.RockCrusher.addRecipe(<ore:gemCharcoal>, false, false, [<Railcraft:dust:3>], [1.0]);
Returns ERROR: /scripts/Crafting.zs:882 > a method available but none matches the parameters (minetweaker.oredict.IOreDictEntry, bool, bool, minetweaker.item.IItemStack[], double[])

I'm running MineTweaker 3.0.9c and ModTweaker 2-0.7b43 in Forge 1272. There are a lot of other mods in my instance I can provide list is needed.

**Comment by Voidi** [comment]
These machines do not use ore dict for there internal recipes.

Workaround:
have a for loop to iterate over all entry in the dict, and add a recipe for every item
Example:
``for item in <ore:logWood>.items {
	CokeOven.addRecipe(item , false, false, terrafirmacraft:item.coal:1, liquid:creosote * 100, 100);
}
``

MAYBE this could done Modtweaker internal itself.

**Comment by Yulife** [comment]
@CovertJaguar commented on something similar to this on the Minetweaker forum.

**Comment by CovertJaguar** [comment]
The Rolling Machine can accept the Forge Ore IRecipes just fine, since its just a clone of the vanilla crafting manager. So yes, the lack of support here is probably a bug.

The others however do not accept Ore Dict entries as inputs directly. In which case looping over the Ore Tag is the correct answer.

**Comment by joshiejack** [comment]
@jaredlll08 We are calling coverts
RailcraftCraftingManager.rollingMachine.addRecipe(output, recipe);

Which I am guessing from what he says (saying it supports ore recipes), just does the normal shaped recipe rather than the ore shaped one. You might have to change it to getRecipes() and new ShapedOreRecipe rather than using his methods.

**Comment by joshiejack** [comment]
or rather our RailcraftHelper.rolling
